name: Automatic Pull Request

on:
  issues:
    types: [opened, reopened]

env:
  SWIFT_IMAGE: swift:5.7-focal

jobs:
  add:
    runs-on: ubuntu-20.04
    if: contains(github.event.issue.labels.*.name, 'Search Help')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD_MAX}}
          # Required recipients' addresses:
          to: ${{secrets.MAIL_RECIPIENTS}}
          # Required sender full name (address can be skipped):
          from: Agora GitHub Notifications
          # Required mail subject:
          subject: Search Issue Created
          # Optional plain body:
          body: |
            Issue [#${{github.event.issue.number}}](${{github.event.issue.url}}) has been created.
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
